export {chunk} from './array/chunk.js'
export {concat} from './array/concat.js'
export {difference} from './array/difference.js'
export {drop} from './array/drop.js'
export {dropRight} from './array/dropRight.js'
export {every} from './array/every.js'
export {filter} from './array/filter.js'
export {find} from './array/find.js'
export {findIndex} from './array/findIndex.js'
export {flatten} from './array/flatten.js'
export {map} from './array/map.js'
export {pull} from './array/pull.js'
export {pullAll} from './array/pullAll.js'
export {reduce} from './array/reduce.js'
export {some} from './array/some.js'
export {slice} from './array/slice.js'
export {uniq} from './array/uniq.js'

export {call} from './function/call.js'
export {apply} from './function/apply.js'
export {bind} from './function/bind.js'
export {debounce} from './function/debounce.js'
export {throttle} from './function/throttle.js'

export {myInstanceOf} from './object/myInstanceOf.js'
export {merge} from './object/merge.js'
export {clone} from './object/clone.js'
export {deepClone} from './object/deepClone.js'

export {axios} from './axios.js'
export {myPromise} from './myPromise.js'